# Generated by Django 5.0 on 2024-08-28 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0002_comment_deleted_at_comment_is_deleted"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="is_removed",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="likes",
        ),
    ]
