# Generated by Django 5.0 on 2024-08-29 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0009_comment_deleted_at_comment_is_deleted_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="parent_comment",
            new_name="parent",
        ),
    ]
