# Generated by Django 5.0 on 2024-08-29 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0010_rename_parent_comment_comment_parent"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="is_deleted",
            new_name="is_removed",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="deleted_at",
        ),
    ]
