# Generated by Django 5.0 on 2024-08-29 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0011_rename_is_deleted_comment_is_removed_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="is_removed",
            new_name="is_deleted",
        ),
        migrations.RenameField(
            model_name="comment",
            old_name="parent",
            new_name="parent_comment",
        ),
        migrations.AddField(
            model_name="comment",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
