# Generated by Django 5.0 on 2024-08-30 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0012_rename_is_removed_comment_is_deleted_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="depth",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
