# Generated by Django 5.0 on 2024-08-26 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='birth_date',
            new_name='birthday',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='profile_picture',
            new_name='images',
        ),
    ]
