# Generated by Django 5.1 on 2024-08-20 01:22

import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='head_image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='blog/images/%Y/%m/%d/'),
        ),
    ]
