# Generated by Django 5.0 on 2024-08-26 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_deleted_at_post_is_deleted'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
