# Generated by Django 5.0 on 2024-08-24 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_post_author_username_comment_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='level',
        ),
    ]
