# Generated by Django 5.0 on 2024-08-26 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_delete_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
