# Generated by Django 5.0 on 2024-08-26 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_delete_comment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="birthday",
        ),
        migrations.RemoveField(
            model_name="post",
            name="location",
        ),
        migrations.AlterField(
            model_name="category",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
