# Generated by Django 5.0 on 2024-08-27 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_remove_post_birthday_remove_post_location_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="category",
            name="is_public",
        ),
        migrations.RemoveField(
            model_name="category",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="post",
            name="deleted_at",
        ),
        migrations.RemoveField(
            model_name="post",
            name="is_deleted",
        ),
    ]
