# Generated by Django 5.1 on 2024-08-21 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_profile_profile_photo_profile_birth_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
