# Generated by Django 5.0 on 2024-08-30 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0009_delete_pageview"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="category",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="tag",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tag",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
